### PR TITLE
Make the package npm publishable

### PR DESCRIPTION
**Pull request by shri3k**
Addresses #42 

# Description 
- Updates the package so that it's publishable to `npm`
- Haven't looked at publishing to `bower` as `bower` has been deprecated

# Notes
To run demos just run `npm run demo` to build bundles for `webpack` and `browserify` or run respective scripts specified in `package.json`. 

@xdamman, I believe since you're the owner of the package - I'll let you decide whose name this package should go under. 
Also, I noticed that this package is named either `selection-share` or `share-selection`. At the moment this package is named `share-selection` according to `package.json` but the project itself is named `selection-sharer`. I believe you should publish it as `selection-sharer` to avoid confusion to former and current users. But it's upto you. :smile_cat: 

Let me know if there's anything that needs to be changed in this PR.

### CODE REVIEW

**Comment by xdamman** [comment]
Feel free to publish it under your name. 
Agreed on keeping the name consistent with the name of the repo. 
Thanks for the great work!

A really cool thing to do would be to make it as a react component.

**Comment by shri3k** [comment]
> A really cool thing to do would be to make it as a react component.
I think we should have a different repo for that as it might confuse people who are not using react on their project.

**Comment by shri3k** [comment]
Just an update on the consistent name. I went ahead and named it `selection-sharer` in npm as well so that it matches the repo name. 
It's now been published [here](https://www.npmjs.com/package/selection-sharer). :tada:

**Comment by xdamman** [comment]
`react-selection-sharer`?

**Comment by shri3k** [comment]
Yeah, I think the naming convention on `react-components` should make that obvious.

**Pull request merged**
